import { Schema, model } from "mongoose";

const bitacoraV1Schema = new Schema({
    numTipo: String,
    docTipo: String,
    nombreCli: String,
    correo: String,
    pagad: String,
    bancSegu: Boolean,
    celular: String,
    tasa: String,
    codOfiDesemb: String,
    ofiDesem : String,
    montSolici: Number,
    montApro: Number,
    plazo: Number,
    modal: String,
    comprAfectDesp: Boolean,
    entidaCompr: String,
    tipoProdCom: String,
    numObligComp: Number,
    cedulEjecu: String,
    nombEjecu: String,
    coordina: String,
    direct: String,
    ciudad: String,
    zona: String,
    estadRadic: String,
    tipoProce: String,
    periodo: Date,
    fechRadica: Date,
    fechDevNeg: Date,
    fechNoV: Date,
    fechDes: Date,
    numCaus: Number,
    causal: String,
    obsDevNeg: String,
    pazSalvo: String,
    soportPag: String,
    obsLegal: String,
    segment: String,
    tipoContr: Boolean,
    estadContr: Boolean,
    cargo: Boolean,
    fechaIngr: Date
});

export default model('bitacoraV1', bitacoraV1Schema);